### ISSUE TITLE
[DSM] Tue Jan 23 2024

### ISSUE THREAD

**Issue by TorinAsakura** [rees46/DSM#3]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by angryforest** [comment]
#### Вчера ушла в тест [DEV-T-2416](https://rees46.jetbrains.space/p/dev/issues/2416)
#### Сегодня [DEV-T-2416](https://rees46.jetbrains.space/p/dev/issues/2416) вернулась на доработку, доработал. Также изучал задачу [DEV-T-2626](https://rees46.jetbrains.space/p/dev/issues/2626) с Одинцовым, смотрел код, пылесосил гугл на предмет похожих проблем. Задача к сожалению не решается логами на стороне импорта, проблема в RabbitMQ. Сергей предложил использовать другой протокол.

**Comment by JusteComte** [comment]
Сегодня [DEV-T-2602](https://rees46.jetbrains.space/p/dev/issues/2602), [DEV-T-2604](https://rees46.jetbrains.space/p/dev/issues/2604) (нашел мутацию которая это решает, и так же проверяю что всего хватает для использование этого, но выводить этот функционал в приложение не вариант)

**Comment by anisimovvb** [comment]
Вчера DEV-T-1974 тестил, немного допилил стили товара/цены.

Сегодня DEV-T-1974 нашёл ещё багу в мобильном клиенте gmail едет вёрстка в сетке 3х3. И для SUPPORT-T-65 пытался собрать среду что бы протестить.

**Comment by yart** [comment]
#### Какие задачи выполнял вчера?
- Добивал [DEV-T-2585](https://rees46.jetbrains.space/p/dev/issues/2585), но задача вернулась после ревью, так как надо дописать к ней тесты.
- Изучал причины возобновления бага в [DEV-T-2123](https://rees46.jetbrains.space/p/dev/issues/2123).

#### Какие задачи будешь делать сегодня?
_Для первого раза пишу в прошедшем времени:_
- Закончил с [DEV-T-2123](https://rees46.jetbrains.space/p/dev/issues/2123), но пришлось вернуться к ней, в связи с запросом по доработке. Заодно, не без активной помощи от Сергея Одинцова, выявил нетипичное поведение методов класса `ActionMailer::Base` в тестах — там, где ожидался `nil`, и по факту метод возвращал `nil`, в ходе автотеста прилетал класс `ActionMailer::Base::NullMail`.
- На момент написания данного сообщения, пишу тесты к [DEV-T-2585](https://rees46.jetbrains.space/p/dev/issues/2585).

**Comment by PNixx** [comment]
Вчера DEV-T-2574
